name: CPP-Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  cpp-build:
    # Name the Job
    name: Build, Test and Package code
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    container: conanio/gcc72

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Update Git
        run: |
          git --version
          sudo apt-get remove git
          sudo apt-get update -y
          sudo apt-get install python-software-properties software-properties-common -y
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get install git -y
          git --version

      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Build code
        run: |
          mkdir build
          cd build
          cmake ..
          cmake . --build
        
