name: CPP-Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  cpp-build:
    # Name the Job
    name: Build, Test and Package code
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build code
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
        
